### ISSUE TITLE
Errors in DataImporting_ArangoDB.sh

### ISSUE THREAD

**Issue by stoerl** [HY-UDBMS/Unibench#1]
Hi, in my opinion there are errors in DataImporting_ArangoDB.sh

- line 13: --server.database must be deleted (produces an error)
- line 36: missing a " at the beginning ./Dataset... -> "./Dataset... (produces an error)

**Comment by Rucchao** [comment]
Hi, thanks for your comments. I have fixed them and updated the release.

Chao
