### ISSUE TITLE
Wrong Queries for ArangoDB

### ISSUE THREAD

**Issue by stoerl** [HY-UDBMS/Unibench#2]
Queries Q2, Q5, Q9 and Q10 in Arango.java contain a collection "PersonHasTag" - but there is no collection "PersonHasTag" in the data ... 
Is this a typo ("PersonHasPost" instead of "PersonHasTag?") or is it the wrong release file for ArangoDB?

**Comment by Rucchao** [comment]
Sorry, it is a typo, it should be "PersonHasPost" instead of "PersonHasTag". Thanks for identifying this issue.

Chao
