### ISSUE TITLE
Ready-made dataset is not importable

### ISSUE THREAD

**Issue by malumoe** [HY-UDBMS/Unibench#3]
I have a problem importing the vendor.csv file into OrientDB with the oetl.sh tool.
The file is from the ready-made dataset you provided in the releases section.

The ETL-Tool terminates with the error

```
2020-01-28 16:12:29:350 SEVER {db=test} ETL process has problem: java.util.concurrent.ExecutionException:
com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record Vendor{Industry:Sports,Country:Australia,Vendor:Elfin_Sports_Cars}: found duplicated key 'null' in index 'Vendor.id' previously assigned to the record #17:0
DB name="test" INDEX=Vendor.id RID=#17:0 [OETLProcessor]Uncaught exception in thread 'pool-2-thread-1'
com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record Vendor{Industry:Sports,Country:Australia,Vendor:Elfin_Sports_Cars}: found duplicated key 'null' in index 'Vendor.id' previously assigned to the record #17:0
```

In the Vendor.json configuration file, the index ist created as follows:
` {"class":"Vendor", "fields":["id:string"], "type":"UNIQUE" }`
Unfortunately, there is no field named `id` and hence, the key is probably 'null'. I guess that's the reason why the import fails

Additionally, I had a look into the vendor.csv file and if I should guess, the key `Vendor` is mentioned as the index key. But unfortunately, some values such as `Signia_(sportswear)` and `Fila_(company)` are doubled. What is the intended index here? Can you please provide a working configuration file for the Vendor.json?

**Comment by Rucchao** [comment]
Hi, thanks for your message. There is a typo for the header of vendor.csv where the Vendor should be id. I have updated the dataset. Thanks for pointing it out and trying to use UniBench.

Chao
