### ISSUE TITLE
Where is the data import script of orientDB？

### ISSUE THREAD

**Issue by xiashengjie** [HY-UDBMS/Unibench#4]
I would like to ask where is the data import script of orientDB?

**Comment by Rucchao** [comment]
Please download SF1 dataset with the importing script at https://github.com/HY-UDBMS/UniBench/releases/tag/0.2

**Comment by xiashengjie** [comment]
The data set generated using Unigen.jar is a little different from the sample data set published, can you share the code to process the generated data set?

**Comment by r00shy** [comment]
OrientDB importing script is there, but there is no script for AgensGraph.
